version: '3.2'
services:
  server:
    working_dir: /home
    image: invicrollc/pathology-viewer:server-latest
    restart: on-failure
    volumes:
      - ../data:/data
    ports:
      - "5000:5000"
    tty: True
  token:
    image: token-service:latest
    restart: on-failure
    environment:
      TOKEN_DURATION: 600
    ports:
      - "5001:5001"
