// module: projects
export const PROJECTS_FETCH_ANNOTATION = 'PROJECTS_FETCH_ANNOTATION';
export const PROJECTS_POST_ANNOTATION = 'PROJECTS_POST_ANNOTATION';
export const PROJECTS_FETCH_DIMENSIONS = 'PROJECTS_FETCH_DIMENSIONS';
export const PROJECTS_FETCH_MLD_CONTENT = 'PROJECTS_FETCH_MLD_CONTENT';
