// module: projects
export const PROJECTS_SET_ACTIVE = 'PROJECTS_SET_ACTIVE';
export const PROJECTS_FETCHING = 'PROJECTS_FETCHING';
export const PROJECTS_SET_ANNOTATION = 'PROJECT_SET_ANNOTATION';
export const PROJECTS_SET_ANNOTATION_FAILED = 'PROJECT_SET_ANNOTATION_FAILED';
export const PROJECTS_SET_DIMENSIONS = 'PROJECTS_SET_DIMENSIONS';

