// module: projects
export const PROJECTS_SET_ACTIVE = 'PROJECTS_SET_ACTIVE';
export const PROJECTS_FETCHING = 'PROJECTS_FETCHING';
export const PROJECTS_SET_ANNOTATION = 'PROJECT_SET_ANNOTATION';
export const PROJECTS_SET_ANNOTATION_FAILED = 'PROJECT_SET_ANNOTATION_FAILED';
export const PROJECTS_SET_DIMENSIONS = 'PROJECTS_SET_DIMENSIONS';

export const PROJECTS_ADD_CLASS = 'PROJECTS_ADD_CLASS';
export const PROJECTS_DELETE_CLASS = 'PROJECTS_DELETE_CLASS';
export const PROJECTS_SET_ACTIVE_CLASS = 'PROJECTS_SET_ACTIVE_CLASS';
export const PROJECTS_ADD_EMPTY_ANNOTATION = 'PROJECTS_ADD_EMPTY_ANNOTATION';

