// module: projects
export const PROJECTS_SET_ACTIVE = 'PROJECTS_SET_ACTIVE';
export const PROJECTS_FETCHING = 'PROJECTS_FETCHING';
export const PROJECTS_SET_ANNOTATION = 'PROJECT_SET_ANNOTATION';
export const PROJECTS_SET_DIMENSIONS = 'PROJECTS_SET_DIMENSIONS';

export const PROJECTS_ADD_CLASS = 'PROJECTS_ADD_CLASS';
export const PROJECTS_DELETE_CLASS = 'PROJECTS_DELETE_CLASS';
export const PROJECTS_DELETE_FEATURES_OF_CLASS = 'PROJECTS_DELETE_FEATURES_OF_CLASS';
export const PROJECTS_ADD_EMPTY_ANNOTATION = 'PROJECTS_ADD_EMPTY_ANNOTATION';
export const PROJECTS_SET_ACTIVE_GEOMETRY = 'PROJECTS_SET_ACTIVE_GEOMETRY';

export const PROJECTS_SET_ACTIVE_CLASS = 'PROJECTS_SET_ACTIVE_CLASS';
export const PROJECTS_UPDATE_CLASS = 'PROJECTS_UPDATE_CLASS';

export const PROJECTS_ANNOTATION_ADD_FEATURE = 'PROJECTS_ANNOTATION_ADD_FEATURE';
export const PROJECTS_SET_MLD_CONTENT = 'PROJECTS_SET_MLD_CONTENT';

export const PROJECTS_SET_FILES = 'PROJECTS_SET_FILES';

export const ANNOTATIONS_PERFORM_UNDO = 'ANNOTATIONS_PERFORM_UNDO';
export const ANNOTATIONS_PERFORM_REDO = 'ANNOTATIONS_PERFORM_REDO';

export const PROJECTS_SET_CONTRAST = 'PROJECTS_SET_CONTRAST';
export const PROJECTS_RESET_CONTRAST = 'PROJECTS_RESET_CONTRAST';
export const PROJECTS_SET_BRIGHTNESS = 'PROJECTS_SET_BRIGHTNESS';
export const PROJECTS_RESET_BRIGHTNESS = 'PROJECTS_RESET_BRIGHTNESS';
